"""add_template_id_to_projects

Revision ID: 5306f255c8d3
Revises: 3bacecabb584
Create Date: 2026-09-28 02:12:53.364832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5306f255c8d3'
down_revision: Union[str, Sequence[str], None] = '3bacecabb584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('template_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'prompt_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'template_id')
    # ### end Alembic commands ###
