"""add_is_current_to_generated_documents

Revision ID: a96a8c02c148
Revises: 5306f255c8d3
Create Date: 2026-09-28 07:48:56.386584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96a8c02c148'
down_revision: Union[str, Sequence[str], None] = '5306f255c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_documents', sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_documents', 'is_current')
    # ### end Alembic commands ###
